config/routes.rb
Ossguidepost::Application.routes.draw do
  devise_for :user, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, :only => [:show, :edit, :update] do
    match ":id" => "projects#show", :as => :project
    resources :projects, :only => :edit
  end

  resources :projects, :only => :update
  resources :project_updates, :only => :update

  resources :github_imports, :only => [:create]

  match "search" => "search#show"

  root :to => 'search#show'

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/import.rb
class Import
  def self.github_import(username)
    raise ArgumentError unless block_given?

    Octokit.repos(username).map { |repo| yield(repo) }
  end

  def self.update_from_origin(project)
    repo = Octokit.repo(project.full_name)

    attrs = {
      :description => repo.description,
      :homepage => repo.homepage,
      :language => repo.language.downcase
    }

    project.update_attributes(attrs)
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user

  validates :name, :length => { :maximum => columns_hash['name'].limit },
                   :presence => true
  validates :full_name, :presence => true,
                   :length => { :maximum => columns_hash['full_name'].limit },
                   :uniqueness => { :scope => :user_id }
  validates :language, :length => { :maximum => columns_hash['language'].limit }

  def self.seeking_maintainer
    where("projects.seeking_maintainer_since IS NOT NULL")
  end

  def seeking_maintainer?
    self.seeking_maintainer_since?
  end

  def seeking_maintainer=(boolean)
    self.seeking_maintainer_since = boolean ? Time.zone.now : nil
  end

  def to_param
    name
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  delegate :username, :to => :github_auth, :prefix => :github, :allow_nil => true
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :registerable, :trackable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email

  has_many :authentications, :dependent => :destroy
    has_one :github_auth, :class_name => "Authentication", 
      :conditions => {:provider => "github"}
  has_many :projects, :dependent => :destroy

  def self.create_with_omniauth(auth)  
    user_info  = auth["info"]
    extra_info = auth["extra"] && auth["extra"]["raw_info"]

    create! do |user|  
      user.email      = user_info["email"].presence

      user.authentications << Authentication.new(
        :provider => auth['provider'], 
        :uid => auth['uid'],
        :username => user_info['nickname'],
        :token => auth["credentials"]["token"]
      )
    end  
  end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/github_imports_controller.rb
class GithubImportsController < ApplicationController
  def create
    Import.github_import(current_user.github_username) do |repo|
      current_user.projects.find_or_create_by_full_name(repo.full_name, 
        :name => repo.name || "unknown",
        :full_name => repo.full_name || "unknown",
        :description => repo.description || "unknown",
        :git_url => repo.git_url || "unknown",
        :homepage => repo.homepage || "unknown",
        :language => repo.language.downcase || "unknown"
      )
    end

    redirect_to user_path(current_user), :notice => "Your github repositories have been imported."
  end
end

app/controllers/project_updates_controller.rb
class ProjectUpdatesController < ApplicationController
  def update
    @project = Project.find(params[:id])

    if Import.update_from_origin(@project)
      redirect_to(user_project_path(current_user, @project), :notice => 'Project was successfully updated.')
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    user = User.find(params[:user_id])
    @project = Project.find_by_name(params[:id])
  end

  def edit
    @user = User.find(params[:user_id])
    @project = Project.find_by_name(params[:id])
  end

  def update
    @project = current_user.projects.find_by_name(params[:id])

    if @project.update_attributes(params[:project])
      redirect_to(user_project_path(current_user, @project), :notice => 'Project was successfully updated.')
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def show
    search = params[:search]

    @difficulties = [
      ["1 - Beginner", 1],
      ["2 - Novice", 2],
      ["3 - Intermediate", 3],
      ["4 - Journeyman", 4],
      ["5 - Master", 5],
    ]

    if search.present?
      @projects = Project.where(:language => search[:language])
      @projects = @projects.where("difficulty <= ?", search[:difficulty].to_i)
      @projects = @projects.search(search[:q]) if search[:q].present?
      @projects = @projects.page(params[:page]).per(10)

      logger.info @projects.inspect
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    provider_session(request.env["omniauth.auth"])
  end

  private

  def provider_session(auth)
    origin = request.env["omniauth.origin"]

    authentication = Authentication.find_by_provider_and_uid(auth["provider"], auth["uid"])

    if authentication
      authentication.update_attribute("token", auth["credentials"]["token"])
      @user = authentication.user
    else
      @user = User.create_with_omniauth(auth)
    end

    respond_to do |format|
      format.html { 
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => auth["provider"].titleize
        sign_in_and_redirect @user, :event => :authentication 
      }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @projects = current_user.projects.order(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/github_imports_helper.rb
module GithubImportsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ossguidepost</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
    <%= link_to_if user_signed_in?, "My Profile", user_path(current_user), :rel => "my_profile-show" %>
  <% else %>
    <%= link_to "Sign in with GitHub", user_omniauth_authorize_path(:github), :rel => "github-authentication" %>
  <% end %>


  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/projects/edit.html.erb
<%= simple_form_for @project do |f| %>
  <%= f.input :difficulty %>

  <%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<dl>
  <dt>Name:</dt>
  <dd><%= @project.name %></dd>

  <dt>Homepage:</dt>
  <dd><%= @project.homepage %></dd>

  <dt>Git URL:</dt>
  <dd><%= @project.git_url %></dd>

  <dt>Description:</dt>
  <dd><%= @project.description %></dd>

</dl>

<%= link_to "Update from Origin", project_update_path(@project.id), :rel => "project-origin_update", :method => :put %>

<!-- Put a big box to the right with the difficulty in it. Really Big!! -->
<div>
  <%= @project.difficulty %>
</div>

app/views/search/show.html.erb
<%= simple_form_for :search, :url => search_path do |f| %>
  <%= f.input :q, :label => "Search", :required => false %>
  <br/>

  <%= f.input :language, :required => false %>
  <br/>

  <%= f.input :difficulty, :collection => @difficulties, :required => false %>
  <br/>

  <%= f.submit "Search" %>
<% end %>

<% if @projects.present? %>
  <div id="search_results">
    <h2>Search Results</h2>

    <%= paginate @projects %>
    <% @projects.each do |project| %>
      <div class="search_result">
        <%= link_to project.name, project_path(project), :rel => "project-view" %>
        <%= project.description %>
        <%= project.difficulty %>
      </div>
    <% end %>
    <%= paginate @projects %>
  </div>
<% end %>

app/views/users/show.html.erb
<%= link_to("GitHub Import", github_imports_path, :method => :post, :rel => "github-import") %>

<% if @projects.present? %>
  <table class='projects-list'>
    <thead>
      <tr>
        <th>Project</th>
        <th>Last Updated</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.name %></td>
          <td><%= project.updated_at.to_s(:short) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>